"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.copyAgent = exports.propertyFilterAgent = exports.dataSumTemplateAgent = exports.totalAgent = void 0;
var total_agent_1 = require("../../experimental_agents/data_agents/total_agent");
Object.defineProperty(exports, "totalAgent", { enumerable: true, get: function () { return total_agent_1.totalAgent; } });
var data_sum_template_agent_1 = require("../../experimental_agents/data_agents/data_sum_template_agent");
Object.defineProperty(exports, "dataSumTemplateAgent", { enumerable: true, get: function () { return data_sum_template_agent_1.dataSumTemplateAgent; } });
var property_filter_agent_1 = require("../../experimental_agents/data_agents/property_filter_agent");
Object.defineProperty(exports, "propertyFilterAgent", { enumerable: true, get: function () { return property_filter_agent_1.propertyFilterAgent; } });
var copy_agent_1 = require("../../experimental_agents/data_agents/copy_agent");
Object.defineProperty(exports, "copyAgent", { enumerable: true, get: function () { return copy_agent_1.copyAgent; } });
