import OpenAI from "openai";
import { AgentFunction, AgentFunctionInfo } from "graphai";
type InputType = string | (string | undefined)[] | undefined;
type OpenAIInputs = {
    model?: string;
    prompt?: InputType;
    system?: InputType;
    mergeablePrompts?: InputType;
    mergeableSystem?: InputType;
    tools?: OpenAI.ChatCompletionTool[];
    tool_choice?: OpenAI.ChatCompletionToolChoiceOption;
    max_tokens?: number;
    verbose?: boolean;
    temperature?: number;
    baseURL?: string;
    apiKey?: string;
    stream?: boolean;
    messages?: Array<Record<string, any>>;
    forWeb?: boolean;
};
export declare const flatString: (input: InputType) => string;
export declare const getMergeValue: (namedInputs: OpenAIInputs, params: OpenAIInputs, key: "mergeablePrompts" | "mergeableSystem", values: InputType) => string;
export declare const openAIAgent: AgentFunction<OpenAIInputs, Record<string, any> | string, string | Array<any>, OpenAIInputs>;
export declare const openAIMockAgent: AgentFunction<{
    model?: string;
    query?: string;
    system?: string;
    verbose?: boolean;
    temperature?: number;
}, Record<string, any> | string, string | Array<any>>;
declare const openaiAgentInfo: AgentFunctionInfo;
export default openaiAgentInfo;
