import { AgentFunctionInfoDictionary } from "@/index";
import {
  sleeperAgent,
  sleeperAgentDebug,
  stringTemplateAgent,
  nestedAgent,
  mapAgent,
  totalAgent,
  bypassAgent,
  echoAgent,
  copyMessageAgent,
  mergeNodeIdAgent,
  countingAgent,
  copy2ArrayAgent,
  pushAgent,
  popAgent,
  shiftAgent,
  streamMockAgent,
} from "@/experimental_agents";

export const defaultTestAgents: AgentFunctionInfoDictionary = {
  bypassAgent,
  echoAgent,
  copyMessageAgent,
  mergeNodeIdAgent,
  sleeperAgent,
  sleeperAgentDebug,
  stringTemplateAgent,
  nestedAgent,
  mapAgent,
  totalAgent,
  countingAgent,
  copy2ArrayAgent,
  pushAgent,
  popAgent,
  shiftAgent,
  streamMockAgent,
};
