export { AgentFunction, AgentFunctionDictonary, GraphData } from "./type";
import { AgentFunctionDictonary, AgentFilterInfo, GraphData, DataSource, ResultDataDictonary, ResultData, DefaultResultData } from "./type";
import { TransactionLog } from "./transaction_log";
import { ComputedNode, StaticNode } from "./node";
import { TaskManager } from "./task_manager";
type GraphNodes = Record<string, ComputedNode | StaticNode>;
export declare class GraphAI {
    readonly version: number;
    private readonly graphId;
    private readonly data;
    private readonly loop?;
    private readonly logs;
    readonly agentFunctionDictionary: AgentFunctionDictonary;
    readonly taskManager: TaskManager;
    readonly agentFilters: AgentFilterInfo[];
    readonly retryLimit?: number;
    nodes: GraphNodes;
    onLogCallback: (__log: TransactionLog, __isUpdate: boolean) => void;
    verbose: boolean;
    private onComplete;
    private repeatCount;
    private createNodes;
    private getValueFromResults;
    private initializeNodes;
    constructor(data: GraphData, agentFunctionDictionary: AgentFunctionDictonary, options?: {
        agentFilters?: AgentFilterInfo[] | undefined;
        taskManager?: TaskManager | undefined;
    });
    getAgentFunction(agentId?: string): import("./type").AgentFunction<any, any, any>;
    asString(): string;
    results<T = DefaultResultData>(all: boolean): ResultDataDictonary<T>;
    errors(): Record<string, Error>;
    private pushReadyNodesIntoQueue;
    private pushQueueIfReady;
    pushQueueIfReadyAndRunning(node: ComputedNode): void;
    pushQueue(node: ComputedNode): void;
    run<T = DefaultResultData>(all?: boolean): Promise<ResultDataDictonary<T>>;
    isRunning(): boolean;
    onExecutionComplete(node: ComputedNode): void;
    private processLoopIfNecessary;
    setLoopLog(log: TransactionLog): void;
    appendLog(log: TransactionLog): void;
    updateLog(log: TransactionLog): void;
    transactionLogs(): TransactionLog[];
    injectValue(nodeId: string, value: ResultData, injectFrom?: string): void;
    resultsOf(sources: Array<DataSource>): ResultData[];
}
